---
modules-search: [ local, global ]

instances:
- id:       ludora
  module:   packages
  config:   packages.conf
- id:       ludora
  module:   packagechooser
  config:   packagechooser.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - packagechooser@ludora
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - grubcfg
  - bootloader
  - dracut
  - shellprocess
  - packages@ludora
  - removeuser
  - umount
- show:
  - finished

branding: ludora

prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
