%global debug_package %{nil}

Name:           lact
Version:        0.10.0
Release:        1%{?dist}
Summary:        GPU control utility
License:        MIT
URL:            https://github.com/ilya-zlobintsev/LACT
# Repackages upstream's own signed Fedora 44 build instead of compiling from
# source: COPR has no network during %%build (cargo needs it to fetch crates
# without a pre-made vendor tarball), and no Rust toolchain is available
# locally to regenerate one. Upstream publishes a Fedora-44-specific binary
# for every release, signed with the key at https://github.com/ilya-zlobintsev/LACT/releases/download/v%{version}/lact.pubkey
Source0:        %{url}/releases/download/v%{version}/lact-%{version}-0.x86_64.fedora-44.rpm
Source1:        https://raw.githubusercontent.com/ilya-zlobintsev/LACT/v%{version}/LICENSE

ExclusiveArch:  x86_64
Requires:       gtk4 libdrm libadwaita libdisplay-info hwdata vulkan-tools clinfo

%description
GPU control utility

%prep
rpm2cpio %{SOURCE0} | cpio -idm
cp %{SOURCE1} .

%build
# nothing to build - repackaging upstream's prebuilt binary

%install
cp -a usr %{buildroot}/

%files
%license LICENSE
/usr/bin/lact
/usr/lib/systemd/system/lactd.service
/usr/share/applications/io.github.ilya_zlobintsev.LACT.desktop
/usr/share/icons/hicolor/512x512/apps/io.github.ilya_zlobintsev.LACT.png
/usr/share/icons/hicolor/scalable/apps/io.github.ilya_zlobintsev.LACT.svg
/usr/share/metainfo/io.github.ilya_zlobintsev.LACT.metainfo.xml
/usr/share/polkit-1/actions/io.github.ilya_zlobintsev.LACT.policy

%changelog
* Thu Aug 20 2026 Lars Søe Mikkelsen <larssoemikkelsen@gmail.com> - 0.10.0-1
- Switch to repackaging upstream's official signed Fedora 44 binary release
  instead of building from source - no Rust toolchain available locally to
  regenerate the cargo vendor tarball the source build needs.
* Sat Jun 28 2026 Lars Søe Mikkelsen <larssoemikkelsen@gmail.com> - 0.9.1-1
- Update to v0.9.1
* Sat Apr 25 2026 - ilya-zlobintsev - v0.9.0
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.9.0 for detailed changelog.
* Sun Jan 25 2026 - ilya-zlobintsev - v0.8.4
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.8.4 for detailed changelog.
* Thu Nov 20 2025 - ilya-zlobintsev - v0.8.3
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.8.3 for detailed changelog.
* Sat Oct 18 2025 - ilya-zlobintsev - v0.8.2
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.8.2 for detailed changelog.
* Thu Aug 07 2025 - ilya-zlobintsev - v0.8.1
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.8.1 for detailed changelog.
* Sat Jun 28 2025 - ilya-zlobintsev - v0.8.0
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.8.0 for detailed changelog.
* Sun May 11 2025 - ilya-zlobintsev - v0.7.4
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.7.4 for detailed changelog.
* Sat Apr 05 2025 - ilya-zlobintsev - v0.7.3
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.7.3 for detailed changelog.
* Sun Mar 16 2025 - ilya-zlobintsev - v0.7.2
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.7.2 for detailed changelog.
* Thu Feb 27 2025 - ilya-zlobintsev - v0.7.1
- Autogenerated from CI, please see https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.7.1 for detailed changelog.
